name: Trigger auto deployment for python-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-container-AutoDeployTrigger-ecd27cc6-1263-4e4a-9871-7bf4b44cda41.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PYTHONCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PYTHONCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PYTHONCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: intuicode.azurecr.io
          registryUsername: ${{ secrets.PYTHONCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: python-container
          resourceGroup: Intuicode
          imageToBuild: intuicode.azurecr.io/python-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


